#!/usr/bin/with-contenv sh


echo "================================="
echo $HL_USER_USERNAME
echo "================================="

source /etc/hluser
chown -R node:node /opt/nodejs
cd /opt/nodejs

exec s6-setuidgid node node app.js
